site_name: Deep Image Matching
repo_url: https://3DOM-FBK.github.io/deep-image-matching
site_author: 3DOM

theme:
  name: readthedocs
  highlightjs: true
  # palette:
  #   primary: indigo
  # font:
  #   text: Open Sans
  features:
    - navigation.path
    - navigation.footer

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [src] # search packages in the src folder
          options:
            show_source: false
            # heading_level: 2

nav:
  - Home: index.md
  - Installation: installation.md
  - Getting started: getting_started.md
  - API Reference:
      - Configuration: config.md
      - Extractors: extractors.md
      - Matchers: matchers.md
      - IO: io.md
      - Utils: utils.md
  - About: about.md
