site_name: Deep Image Matching
repo_url: https://3DOM-FBK.github.io/deep-image-matching
site_author: 3DOM

theme:
  name: readthedocs
  palette:
    primary: indigo
  font:
    text: Open Sans
  features:
    - navigation.path
    - navigation.footer

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src] # search packages in the src folder
          options:
            show_source: false

nav:
  - Home: index.md
  - Installation: installation.md
  - Getting started: getting_started.md
  - API Reference:
      - Configuration: config.md
      - Extrctors: extractors.md
      - Matchers: matchers.md
      - IO: io.md
      - Utils: utils.md
  - About: about.md
