# User configuration file

general:
  tile_size: (2000, 2000)
  geom_verification: pydegensac
  min_inliers_per_pair: 10
  min_inlier_ratio_per_pair: 0.15
  gv_threshold: 1

extractor:
  name: "aliked"
  model_name: aliked-n16rot
  max_num_keypoints: 960
  detection_threshold: 0.2
  nms_radius: 3

matcher:
  name: "lightglue"
  n_layers: 9
  depth_confidence: 0.95 # early stopping, disable with -1
  width_confidence: 0.99 # point pruning, disable with -1
  filter_threshold: 0.10 # match threshold
