general:
  camera_model: "pinhole" # ["simple-pinhole", "pinhole", "simple-radial", "opencv"]
  openmvg_camera_model: "pinhole_radial_k3" # ["pinhole", "pinhole_radial_k3", "pinhole_brown_t2"]
  single_camera: True

cam0:
  camera_model: "pinhole"
  images : ""

cam1:
  camera_model: "pinhole"
  images : "DSC_6468.jpg,DSC_6468.jpg"