general:
  camera_model: "simple-pinhole" # ["simple-pinhole", "pinhole", "simple-radial", "opencv"]
  single_camera: False

cam0:
  camera_model: "pinhole"
  images : "DSC_6466.JPG,DSC_6467.JPG"

cam1:
  camera_model: "pinhole"
  images : ""