general:
  camera_model: "simple-radial" # ["simple-pinhole", "pinhole", "simple-radial", "opencv"]
  openmvg_camera_model: "pinhole_radial_k3" # ["pinhole", "pinhole_radial_k3", "pinhole_brown_t2"]
  single_camera: False
  intrinsics: ~  # None

cam0:
  camera_model: "pinhole"
  intrinsics: [
    1200, 1200, 500, 750
  ]
  images : "*.JPG"


cam1:
  camera_model: "pinhole"
  intrinsics: [
    1200, 1200, 750, 500
  ]  
  images : "DSC_6468.JPG,DSC_6469.JPG"