# User configuration file

general:
  tile_size: (2000, 2000)
  geom_verification: pydegensac
  min_inliers_per_pair: 10
  min_inlier_ratio_per_pair: 0.15
  gv_threshold: 1

extractor:
  name: keynetaffnethardnet
  n_features: 8000
  upright: True

matcher:
  name: "kornia_matcher"
  match_mode: smnn
  th: 0.95
