# User configuration file

general:
  tile_size: (448, 448) # Roma always uses 448x448 tiles
  tile_overlap: 0 # It is suggested to use 0 overlap to not increase the number of tiles
  geom_verification: ransac # ransac is suggested with a large number of matches (pydegensac may have issues with very large datasets)
  min_inliers_per_pair: 10
  min_inlier_ratio_per_pair: 0.05
  gv_threshold: 1

extractor:
  name: "no_extractor"

matcher:
  name: "roma"
