# User configuration file

general:
  tile_size: (2400, 2000)
  geom_verification: pydegensac
  min_inliers_per_pair: 10
  min_inlier_ratio_per_pair: 0.25

extractor:
  name: "superpoint"
  max_keypoints: 8000 # -1 no limits
  nms_radius: 4
  keypoint_threshold: 0.005
  remove_borders: 4
  fix_sampling: False

matcher:
  name: "superglue"
  weights: "outdoor"
  sinkhorn_iterations: 20
  match_threshold: 0.3